# Generated by Django 4.2.4 on 2023-08-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_permalink'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imagelink',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Hubert_van_Eyck_023.jpg/800px-Hubert_van_Eyck_023.jpg'),
            preserve_default=False,
        ),
    ]
