# Generated by Django 4.2.4 on 2023-09-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(default='testing', max_length=128),
            preserve_default=False,
        ),
    ]
