# Generated by Django 4.2.4 on 2023-10-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured',
            field=models.CharField(blank=True, null=True),
        ),
    ]
